#!/usr/bin/env bash
# Installs and configures HAproxy on webserver 3, distributes requests
# using a roundrobin algorithm

# echo "
# 18.209.223.58 19037-lb-01
# 52.91.120.191 19037-web-02
# 3.84.238.247 19037-web-01
# " | sudo tee -a /etc/hosts 

sudo apt-get update
sudo apt-get upgrade

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 19037-web-01 100.25.31.96:80 check
    server 19037-web-02 107.23.94.25:80 check
"
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
