#!/usr/bin/env bash
# This will print "Best school" 10 times using the while loop

counter=1
while [ $counter -le 10 ]
do
	if [ $counter == 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
