#!/usr/bin/env bash
# Make nginx run as nginx
pkill -f apache2
sed -i '1i user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
